blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussions
    url: https://github.com/genesis-synth/genesis/discussions
    about: Ask questions and discuss ideas
  - name: ğŸ“š Documentation
    url: https://genesis-synth.github.io/genesis
    about: Check documentation before opening an issue
